# -*- coding: utf-8 -*-
"""Python Assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uHnndhW3zO3VNz8gqokqchEutok5v7eP

<!DOCTYPE html>
<html>
<body>

  <h1><b> Data Analytics (DA) <b> </h1>
  <h2><b>Python Assignment 2- Data Structures - List, Dictionary, Set & Conditional Statements <b></h2>

</body>
</html>

**Problem Statement:**

This assignment focuses on working with core data structures such as lists,
dictionaries, and sets, along with implementing conditional statements.
The objective is to develop a strong understanding of:

*   List creation, modification, and access operations
*   Dictionary creation and manipulation using key-value pairs
*   Set properties and operations like uniqueness, union, and intersection
*   Decision-making using conditional statements (if, elif, else)

<h1><u><b>Task<b></u><h1>


*   List (Creation, Modification, and Access)

        *   List Creation
        *   List Operations / Modifications
        *   Accessing List Elements

*   Dictionary (Creation, Modification and Access)
*   Sets (Operations)
*   Operators & Conditional Statements : (IF, ELIF, ELSE)

<h3><b>List (Creation, Modification, and Access):<b><h3>

<h3><b>1.   List Creation: <b><h3>


      a. Create a list named age_list with five integer elements. For eg., [24, 25, 27, 28 ,29]
"""

Age_list=[24,25,35,48,59]
print(type(Age_list))

"""    b. Create a list named name_list with five string elements."""

Name_list = ["Harsha","Joesph","Vijay","Aathira","Athithi"]
print(type(Name_list))

"""<h2><b>2. List Operations / Modifications:<b><h2>

   **a. Append the string "Yazhini" to name_list.**
"""

Name_list.append("Yazhini")
Name_list

"""   **b. Insert the element 26 at index 2 in age_list.**"""

Age_list.insert(2,26)
Age_list

"""   **c. Remove the string "Yazhini" from name_list.**"""

Name_list.remove("Yazhini")
Name_list

"""  **d. Pop the last element from age_list.**"""

Age_list.pop(-1) # If index is empty alsi default pop the last element
Age_list

""" **e. Extend the age_list with additional ages [31,30,32].**"""

Age_list.extend([31,30,32])
Age_list

"""**f. Sort age_list in descending order.**"""

Age_list.sort()
Age_list

"""**g. Find the max age, min age, and sum of all ages from age_list.**"""

# Max Age
Max_Age= max(Age_list)
print(f'Max_Age:{Max_Age}')

# Min Age
Min_Age= min(Age_list)
print(f'Min_Age:{Min_Age}')

# Sum of all Age
Sum_Age=sum(Age_list)
print(f'Sum_Age:{Sum_Age}')

"""<h3><b>3. Accessing List Elements:<b><h3>
    <p><b>a. Print the first element of name_list.<b><p>
"""

Name_list

Name_list[0]

"""**b. Print the last element of name_list.**"""

Name_list[-1]

"""**c. Print the elements from index 2 to index 4 in name_list.**"""

Name_list[2:5]

"""**d. Print the elements of name_list in reverse order.**"""

Name_list.reverse()
Name_list

"""<h3><b>Dictionary (Creation, Modification and Access):<b><h3>

<b>a. Create a dictionary named student_marks that maps the names of five students to their marks (use a scale of 0 to 100).<b>
"""

Student_marks={
    "Yazhini":85,
   "Athithi":76,
    "Aathira":65,
    "Vijay":35,
    "Joesph":25,
    "Harsha":94
}
Student_marks

"""**b. Access and print the mark of a specific student of your choice.**"""

Student_marks["Vijay"]

"""**c. Add a new student, "Janani," with a mark of 80 to the student_marks dictionary.**"""

Student_marks["Janani"]=80
Student_marks

"""**d. Update the mark of any one older student to 82.**"""

Student_marks["Vijay"]=82
Student_marks

"""**e. Use the keys(), values(), and items() methods to print all keys, values, and key-value pairs in the student_marks dictionary.**"""

# Keys()
Student_marks.keys()

#values()
Student_marks.values()

# Items()
Student_marks.items()

"""<h3><b>Sets (Operations):<b><h3>

**a. Create a set called my_set with the following values: ['a','e','i','o','u','a','a','i'] Analyze the output and explain the same.**
"""

My_Set={"a","e","i","o","u","a","a","i"} #
My_Set

"""**b. Attempt to access my_set[4]. If the code throws an error, provide an explanation.**"""

My_Set[4]

"""**Explaination:**

The error is tells that in a set we can't able access the element by using indexing[o] like,

bacause its unchangable and its not stored like 1st, 2nd position

If i want ti access the element convert as list and perform.

**c. Create two sets:**

* set1 with values: {1, 3, 5, 7, 9}
* set2 with values: {2, 3, 5, 8, 10}
"""

Set1={1,3,5,7,9}
Set2={2,3,5,8,10}
Set1
Set2

"""**d. Compute and print the union and intersection of set1 and set2.**"""

# Union
Set1.union(Set2)

# Intersection
Set1.intersection(Set2)

"""<h3><b>Operators & Conditional Statements : (IF, ELIF, ELSE)<h3><b>

<h4><b>Performance Category Program:<h4><b>

**1. Prompt the user for input. Score range should be from 0 to 10 (both inclusive).**
"""

Score=int(input("Enter the score between 0 and 10: "))

if 0<=Score<=10:
  print(f'Enterd valied score {Score}')
else:
  print("The Score must be between 0 and 10")

"""**2. Find the performance category based on the input score using the following criteria:**

* a. Above Average: Score greater than 7
* b. Average: Score between 4 and 7 (both inclusive)
* c. Below Average: Score less than 4
"""

Score=int(input("Enter the Score: "))

if 0<=Score<=10:
  if Score>7:
    print("Above Average:")
  elif 4<=Score<=7:
    print("Average")
  else:
   print("Below Average")
else:
  print("Enter score between 0 to 10")

"""**3. Output: Print the Performance category**"""

Score=int(input("Enter the Score: "))

if 0<=Score<=10:
  if Score>7:
    print("Performance Category: Above Average:")
  elif 4<=Score<=7:
    print("Performance Category: Average")
  else:
   print("Performance Category: Below Average")
else:
  print("Enter score between 0 to 10")

"""**4. Additional Step: You can give a prompt of your choice to each category. For example, if the score is below average,**

“Need to improve your performance; consistent practice
will lead to better results”.
"""

Score=int(input("Enter the Score: "))

if 0<=Score<=10:
  if Score>7:
    print("Performance Category: Above Average:")
  elif 4<=Score<=7:
    print("Performance Category: Average")
  else:
   print("Performance Category: Below Average")
   print("Need to improve your performance; consistent practice will lead to better results")
else:
  print("Enter score between 0 to 10")

"""<h1><b>!!!!!!!!!!!! Thank You !!!!!!!!!!!!!!<b><h1>"""